[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.build]
run_task = { name = [
    "build-awspolly",
    "build-deepgram",
    "build-elevenlabs",
    "build-googlecloud",
] }

[tasks.build-portable]
run_task = { name = [
    "build-awspolly-portable",
    "build-deepgram-portable",
    "build-elevenlabs-portable",
    "build-googlecloud-portable",
] }

[tasks.release-build]
run_task = { name = [
    "release-build-awspolly",
    "release-build-deepgram",
    "release-build-elevenlabs",
    "release-build-googlecloud",
] }

[tasks.release-build-portable]
run_task = { name = [
    "release-build-awspolly-portable",
    "release-build-deepgram-portable",
    "release-build-elevenlabs-portable",
    "release-build-googlecloud-portable",
] }

[tasks.build-deepgram]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-tts-deepgram"]


[tasks.build-deepgram-portable]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-tts-deepgram", "--no-default-features"]


[tasks.build-awspolly]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-tts-awspolly"]

[tasks.build-awspolly-portable]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-tts-awspolly", "--no-default-features"]

[tasks.build-elevenlabs]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-tts-elevenlabs"]

[tasks.build-elevenlabs-portable]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-tts-elevenlabs", "--no-default-features"]

[tasks.build-googlecloud]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-tts-googlecloud"]

[tasks.build-googlecloud-portable]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-tts-googlecloud", "--no-default-features"]

[tasks.release-build-deepgram]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-tts-deepgram", "--release"]

[tasks.release-build-deepgram-portable]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = [
    "build",
    "-p",
    "golem-tts-deepgram",
    "--release",
    "--no-default-features",
]

[tasks.release-build-awspolly]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-tts-awspolly", "--release"]

[tasks.release-build-awspolly-portable]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = [
    "build",
    "-p",
    "golem-tts-awspolly",
    "--release",
    "--no-default-features",
]

[tasks.release-build-elevenlabs]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-tts-elevenlabs", "--release"]

[tasks.release-build-elevenlabs-portable]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-tts-elevenlabs", "--release", "--no-default-features"]

[tasks.release-build-googlecloud]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-tts-googlecloud", "--release"]

[tasks.release-build-googlecloud-portable]
install_crate = { crate_name = "cargo-component", version = "0.20.0" }
command = "cargo-component"
args = ["build", "-p", "golem-tts-googlecloud", "--release", "--no-default-features"]

[tasks.wit-update]
install_crate = { crate_name = "wit-deps-cli" }
command = "wit-deps"
args = ["update"]

[tasks.wit]
dependencies = ["wit-update"]

script_runner = "@duckscript"
script = """
modules = array tts googlecloud awspolly elevenlabs openrouter ollama deepgram

for module in ${modules}
    rm -r ${module}/wit/deps
    mkdir ${module}/wit/deps/golem-tts
    cp wit/golem-tts.wit ${module}/wit/deps/golem-tts/golem-tts.wit
    cp wit/deps/io ${module}/wit/deps

    echo "Copied WIT for module tts::${module}"
end

# Copy WIT files for integration tests
rm -r ../test/tts/wit
mkdir ../test/tts/wit/deps/golem-tts
mkdir ../test/tts/wit/deps/io
cp wit/golem-tts.wit ../test/tts/wit/deps/golem-tts/golem-tts.wit
cp wit/deps/io/error.wit ../test/tts/wit/deps/io/error.wit
cp wit/deps/io/poll.wit ../test/tts/wit/deps/io/poll.wit
cp wit/deps/io/streams.wit ../test/tts/wit/deps/io/streams.wit
cp wit/deps/io/world.wit ../test/tts/wit/deps/io/world.wit

echo "Copied WIT for module test"
"""

[tasks.build-test-components]
dependencies = ["build"]
description = "Builds tts test components with golem-cli"
script = '''
cd ../test/tts

golem-cli --version
golem-cli app clean
golem-cli app build -b awspolly-debug
golem-cli app clean
golem-cli app build -b elevenlabs-debug
golem-cli app clean
golem-cli app build -b googlecloud-debug
golem-cli app clean
golem-cli app build -b openrouter-debug
golem-cli app clean
golem-cli app build -b ollama-debug
golem-cli app clean
golem-cli app build -b deepgram-debug
'''
